package com.elualves.app.view;

import com.elualves.app.dao.DAOPorta;
import com.elualves.app.dao.DAOValidaIP;
import com.elualves.app.model.ModelPorta;
import com.elualves.app.service.ServidorService;
import com.elualves.app.util.TrasformaIpCodigo;
import com.elualves.app.util.Utilitarios;
import com.elualves.app.util.ValidaIP;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ViewServidor extends javax.swing.JFrame {

    public ViewServidor() throws ClassNotFoundException, UnknownHostException, SQLException {
        initComponents();
        Utilitarios ut = new Utilitarios();
        ut.inserirIcone2(this);
        setLocationRelativeTo(null);

        TrasformaIpCodigo tic = new TrasformaIpCodigo();
        DAOPorta dp = new DAOPorta();
        String recebeIp = tic.recebeIp();
        jTFCodigoIp.setText(recebeIp);
        String recebePortaBanco = String.valueOf(dp.buscaGetPorta().getCodigo());
        jTFPorta.setText(recebePortaBanco);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnAtivarServidor = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFCodigoIp = new javax.swing.JTextField();
        btnAlterarPorta = new javax.swing.JButton();
        btnCopiarPorta = new javax.swing.JButton();
        jTFPorta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCopiarPorta1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jButton3.setText("jButton3");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 74, 173)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAtivarServidor.setBackground(new java.awt.Color(255, 255, 255));
        btnAtivarServidor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtivarServidor.setForeground(new java.awt.Color(0, 74, 173));
        btnAtivarServidor.setText("Ativar Servidor");
        btnAtivarServidor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 173), 1, true));
        btnAtivarServidor.setContentAreaFilled(false);
        btnAtivarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarServidorActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 74, 173));
        btnSair.setText("Sair");
        btnSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 173), 1, true));
        btnSair.setContentAreaFilled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 74, 173));
        jLabel1.setText("Código");

        jLabel3.setForeground(new java.awt.Color(0, 74, 173));
        jLabel3.setText("Porta");

        jTFCodigoIp.setEditable(false);
        jTFCodigoIp.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigoIp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFCodigoIp.setForeground(new java.awt.Color(255, 0, 0));
        jTFCodigoIp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jTFCodigoIp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFCodigoIpMousePressed(evt);
            }
        });
        jTFCodigoIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoIpActionPerformed(evt);
            }
        });

        btnAlterarPorta.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarPorta.setForeground(new java.awt.Color(0, 74, 173));
        btnAlterarPorta.setText("Alterar Porta");
        btnAlterarPorta.setAutoscrolls(true);
        btnAlterarPorta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        btnAlterarPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPortaActionPerformed(evt);
            }
        });

        btnCopiarPorta.setBackground(new java.awt.Color(255, 255, 255));
        btnCopiarPorta.setForeground(new java.awt.Color(0, 74, 173));
        btnCopiarPorta.setText("Copiar Porta");
        btnCopiarPorta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        jTFPorta.setForeground(new java.awt.Color(0, 74, 173));
        jTFPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPortaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 74, 173));
        jLabel6.setText("Painel de Controle do Servidor Vênus");

        btnCopiarPorta1.setBackground(new java.awt.Color(255, 255, 255));
        btnCopiarPorta1.setForeground(new java.awt.Color(0, 74, 173));
        btnCopiarPorta1.setText("Copiar Código");
        btnCopiarPorta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTFPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnAlterarPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCodigoIp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCopiarPorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCopiarPorta1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtivarServidor)
                        .addGap(10, 10, 10)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAtivarServidor, btnSair});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterarPorta, btnCopiarPorta, btnCopiarPorta1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCodigoIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCopiarPorta1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlterarPorta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFPorta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(btnCopiarPorta)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtivarServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAtivarServidor, btnSair});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterarPorta, btnCopiarPorta, btnCopiarPorta1, jTFCodigoIp, jTFPorta});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAtivarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarServidorActionPerformed
        setVisible(false);
         new ServidorService();
    }//GEN-LAST:event_btnAtivarServidorActionPerformed

    private void jTFCodigoIpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCodigoIpMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoIpMousePressed

    private void jTFPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPortaActionPerformed

    private void btnAlterarPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPortaActionPerformed

        String valorDaPorta = jTFPorta.getText();
        DAOPorta dp = new DAOPorta();
        try {
            dp.atualizarPorta(valorDaPorta);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlterarPortaActionPerformed

    private void jTFCodigoIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoIpActionPerformed


    }//GEN-LAST:event_jTFCodigoIpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("null")
            public void run() {

                try {

                    ValidaIP vi = new ValidaIP();

                    DAOValidaIP daovip = new DAOValidaIP();
                    ValidaIP vip = new ValidaIP();
                    DAOValidaIP dip = new DAOValidaIP();
                    ViewAvisoIpAlterado vaia = new ViewAvisoIpAlterado();

                    //******************************************************************************
                    String ipBanco = vip.buscaIPNoBanco();
                    String ipMaquina = vi.getIpLocalhost();
                    int contaLinhaBanco = dip.buscaContagemDeRegistros();
                    //******************************************************************************
                    //ver CapturaIp e ValidaIP==>>modificar para programar sem internet
                    if (ipMaquina == null) {
                        ViewAvisoConectar vac = new ViewAvisoConectar();
                        vac.setVisible(true);
                    }
                    //******************************************************************************    
                    if (contaLinhaBanco < 1) {
                        try {
                            daovip.salvarIPDAO();
                            ViewServidor vs = new ViewServidor();
                            vs.setVisible(true);
                        } catch (ClassNotFoundException | UnknownHostException | SQLException ex) {
                            Logger.getLogger(ViewServidor.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    //******************************************************************************
                    if (contaLinhaBanco == 1 && ipMaquina.equals(ipBanco) && ipMaquina != null) {
                        ViewServidor vs = new ViewServidor();
                        vs.setVisible(true);
                    } else if (contaLinhaBanco == 1 && !ipMaquina.equals(ipBanco) && ipMaquina != null) {
                        vaia.setVisible(true);
                    }
                    //****************************************************************************

                } catch (SQLException | ClassNotFoundException | UnknownHostException ex) {
                    Logger.getLogger(ViewServidor.class.getName()).log(Level.SEVERE, null, ex);
                }
                //********************************************************************************
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPorta;
    private javax.swing.JButton btnAtivarServidor;
    private javax.swing.JButton btnCopiarPorta;
    private javax.swing.JButton btnCopiarPorta1;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTFCodigoIp;
    private javax.swing.JTextField jTFPorta;
    // End of variables declaration//GEN-END:variables
}
